"""Generate JSON Schema and TypeScript from the canonical models + ontology manifest."""

import json
from pathlib import Path

from urbanimpact import contracts as c
from urbanimpact.util import digest

from ontology.registry import validate_registry

MODELS = [
    c.Scenario,
    c.CityPack,
    c.OntologyObject,
    c.Link,
    c.ActionRequest,
    c.ActionRecord,
    c.ProjectionSpec,
    c.Metric,
    c.ResultBundle,
]


def ts_type(s):
    if "$ref" in s:
        return s["$ref"].split("/")[-1]
    if "const" in s:
        return json.dumps(s["const"])
    if "enum" in s:
        return " | ".join(json.dumps(v) for v in s["enum"])
    if "anyOf" in s:
        return " | ".join(ts_type(v) for v in s["anyOf"])
    t = s.get("type")
    if t == "array":
        if "prefixItems" in s:
            return "[" + ", ".join(ts_type(x) for x in s["prefixItems"]) + "]"
        return "(" + ts_type(s.get("items", {})) + ")[]"
    if t == "object":
        if "properties" not in s:
            extra = s.get("additionalProperties", {})
            return "Record<string, " + (ts_type(extra) if isinstance(extra, dict) else "unknown") + ">"
        req = s.get("required", [])
        return (
            "{\n"
            + "".join(
                "  " + json.dumps(k) + ("" if k in req else "?") + ": " + ts_type(v) + ";\n"
                for k, v in s["properties"].items()
            )
            + "}"
        )
    return {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(t, "unknown")


def outputs():
    validate_registry()
    schemas = {m.__name__: m.model_json_schema() for m in MODELS}
    defs = {}
    for name, schema in schemas.items():
        for k, v in schema.get("$defs", {}).items():
            if k in defs and defs[k] != v:
                raise ValueError("Conflicting model definitions")
            defs[k] = v
        defs[name] = {k: v for k, v in schema.items() if k != "$defs"}
    result = {
        f"contracts/generated/{name}.schema.json": json.dumps(schema, indent=2) + "\n"
        for name, schema in schemas.items()
    }
    result["web/src/generated/contracts.ts"] = (
        "// Generated by python -m ontology.codegen; do not edit.\n"
        + "".join("export type " + k + " = " + ts_type(v) + ";\n" for k, v in sorted(defs.items()))
    )
    result["contracts/generated/ontology-bindings.json"] = (
        json.dumps(
            {
                "ontology_hash": digest(c.MANIFEST),
                "object_types": [x.value for x in c.ObjectType],
                "link_types": [x.value for x in c.LinkType],
                "action_types": [x.value for x in c.ActionType],
            },
            indent=2,
        )
        + "\n"
    )
    return result


def main():
    import argparse

    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    for name, content in outputs().items():
        path = Path(name)
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit("Stale generated binding: " + name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    print("Ontology / Python / JSON Schema / TypeScript bindings consistent")


if __name__ == "__main__":
    main()
